version: '3.4'

services:
  firehose:
    image: bsky-firehose
    build:
      context: ..
      dockerfile: ./Firehose/dockerfile
    volumes:
      - ./Firehose/appsettings.json:/app/appsettings.json
