version: '3.4'

services:
  blueskyfeed:
    image: blueskyfeed
    build:
      context: .
      dockerfile: BlueskyFeed/Dockerfile

  blueskyfeed.setup:
    image: blueskyfeed.setup
    build:
      context: .
      dockerfile: BlueskyFeed.Setup/Dockerfile
