version: '3.4'

services:
  firehose:
    image: bsky-firehose
    build:
      context: .
      dockerfile: ./Firehose/dockerfile
    volumes:
      - ./Firehose/appsettings.json:/app/appsettings.json
  feed:
    image: bsky-feed
    build:
      context: .
      dockerfile: ./Feed/dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./Feed/appsettings.json:/app/appsettings.json