FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /App

# Copy common
COPY ./Common ./Common
RUN dotnet restore ./Common/Common.csproj

# Copy Feed
COPY ./Feed ./Feed
# Restore as distinct layers
RUN dotnet restore ./Feed/BlueskyFeed.csproj
# Build and publish a release
RUN dotnet publish -c Release -o out ./Feed/BlueskyFeed.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "BlueskyFeed.dll"]