version: '3.4'

services:
  bsky:
    image: bsky-feed
    build:
      context: ..
      dockerfile: ./Feed/dockerfile
    ports:
      - 5000:80
    volumes:
      - ./Feed/appsettings.json:/App/appsettings.json